version: "3.9"

services:
  web:
    image: issuejong/piro-cardgame:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      DEBUG: "0"
      SECRET_KEY: "change-me"
      ALLOWED_HOSTS: "localhost,127.0.0.1"